// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use pooler with transaction mode (port 6543) for Supabase
    url: "postgresql://postgres.pfjkpwqxvasrijxyhklp:Bpm%21geas2026@aws-1-us-east-2.pooler.supabase.com:6543/postgres",
  },
});
